### ISSUE TITLE
Output only found security vulnerabilities?

### ISSUE THREAD

**Issue by kristapsk** [nunomaduro/patrol#10]
Is there a way to run `patrol` to just output found security vulnerabilities, if there are any, otherwise be quiet? Would be useful for automatic checks from crontab, which would send e-mail only if there is security updates that should be applied.

**Comment by ArielMejiaDev** [comment]
At this moment there is no flag to execute this behavior, but you can make a PR, and add your own handler to get the behavior that you expect.
