### ISSUE TITLE
Implement a progress bar while scanning

### ISSUE THREAD

**Issue by MuriloChianfa** [nunomaduro/patrol#13]
Hi guys, while i scanning my project with patrol, this take a long time to complete run.
My project has 191 dependencies, and I think it would be really cool to have a progress bar during analysis.

![image](https://github.com/nunomaduro/patrol/assets/60560085/4dd420ea-5db7-49bd-b392-1c5eb355eadd)

What do you guys think about?

**Comment by nunomaduro** [comment]
Good idea, can you PR it?
