### ISSUE TITLE
Possible DivisionByZeroError in Score.php

### ISSUE THREAD

**Issue by grezlikowski** [nunomaduro/patrol#2]
Fatal error: Uncaught DivisionByZeroError: Division by zero in C:\Laragon\www\exea365\vendor\nunomaduro\patrol\src\Handlers\Score.php:53

**Comment by nunomaduro** [comment]
@grezlikowski Can you submit a pull request to address that issue?

**Comment by gerpo** [comment]
@grezlikowski  Did you run it on Windows?

Had the same issue on a Windows 10 machine and tracked it down to the way the composer commands are run. 
The line  `(new ExecutableFinder())->find('composer')` returns the composer.BAT file, and the way the commands are constructed this file is passed to php to be executed resulting in the exception down the line. 
A quickfix is to comment out the line `(new PhpExecutableFinder())->find()` in the [ComposerBinary.php](https://github.com/nunomaduro/patrol/blob/56aff8b38988c08cfcef874845e004305e5cb53c/src/Support/ComposerBinary.php#L138) like below.

If I find some time I will try to submit a pull request.

```php
private function run(array $commands): array
    {
        return collect($commands)->map(function ($command) {
            if (isset(self::$cache[$command])) {
                return [self::$cache[$command], $command];
            }

            tap($process = new Process([
                //(new PhpExecutableFinder())->find(),
                (new ExecutableFinder())->find('composer'),
                ...explode(' ', $command),
            ], (string) realpath($this->directory)))->start();

            return [$process, $command];
        })->map(
            fn ($result) => $result[0] instanceof Process
                ? (self::$cache[$result[1]] = tap($result[0], fn ($result) => $result->wait())->getOutput())
                : $result[0]
        )->toArray();
}
```

**Comment by nunomaduro** [comment]
@gerpo Fell free to pull request something on the windows stuff.

**Comment by TBoileau** [comment]
@nunomaduro @gerpo I work on it ;) I think I can make my pull request in the afternoon

EDIT : nevermind, @rogervila was to quick :)

**Comment by grezlikowski** [comment]
> @grezlikowski Did you run it on Windows?

Yes, Windows 10, PHP 8.0.6, Composer 2.0.13.
