### ISSUE TITLE
patrol timeout on getting composer list 

### ISSUE THREAD

**Issue by ariaieboy** [nunomaduro/patrol#9]
hi 
here is my output 
![image](https://user-images.githubusercontent.com/15873972/122447628-2fa25800-cfb9-11eb-8c5c-6542dc83b5fc.png)

php version : 8.0.7 
composer version : 2.1.3

tested on locall machine and sail container

**Comment by ArielMejiaDev** [comment]
Tested with the same PHP version and the same composer version in a fresh project and it works.

**Comment by vbasky** [comment]
I get the same issue on a PHP 8.0.8 and Composer 2.1.3 project. Can we please test this once more. I have it happen both on local install and sail
